from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    # Append the message to the list rather than overwriting the history
    messages: Annotated[List[BaseMessage], add_messages]

    # Inputs from the user
    ticker: str
    user_query: str

    # JSON plan generated by the first agent
    plan: Dict[str, Any]

    # Raw data fetched in parallel from tools (Stock, News, SEC)
    stock_data: Optional[Dict[str, Any]]
    news_data: Optional[Dict[str, Any]]
    sec_data: Optional[Dict[str, Any]]

    # Intermediate analysis and the final drafted report
    analysis: str
    memo: str

    # Feedback from the critique agent 
    critic_feedback: Optional[str]
    review_status: Optional[str]
    revision_count: int

    # Output path for the generated PDF document
    pdf_path: Optional[str]